encyclopedia/urls.py
from django.urls import path

from . import views
app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("create-page",views.createEntry, name='create-entry'),
    path("wikipedia/<str:entry>",views.getEntry, name='entry-url'),
    path("wikipedia/<str:entry>/edit",views.editEntry, name='edit-entry'),
    path("random-page",views.randomEntry, name='random-entry'),
    path("search", views.searchEntry, name='search-entry'),
    path("<str:entry>/edit", views.editEntry,name="EditEntry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from logging import PlaceHolder
from django import forms
class CreateEntry(forms.Form):
    title = forms.CharField(max_length=100,required=True)
    description = forms.CharField(widget=forms.Textarea,required=True)
class SearchEntry(forms.Form):
    entry = forms.CharField(max_length=100,required=False, widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))
class EditEntry(forms.Form):
    body = forms.CharField(widget=forms.Textarea,required=True)

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import *
from . import util
from markdown2 import markdown
import random
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })
def createEntry(request):
    ef = CreateEntry(request.POST)
    title = request.POST.get('title')
    description = request.POST.get('description')
    context = {
        'ef': ef
    }
    if ef.is_valid():
        util.save_entry(title,description)
        entry = util.get_entry(title)
        return HttpResponseRedirect('wikipedia/' + title)
    else:
        return render(request, 'encyclopedia/create-entry.html', context)
def getEntry(request, entry):
    entry = util.get_entry(entry)
    try:
        entry = markdown(entry)
        return render(request, 'encyclopedia/entrys.html',{'entry':entry})
    except TypeError:
        return render(request, 'encyclopedia/entrys.html',{'entry':entry})
def randomEntry(request):
    entrys = random.choice(util.list_entries())
    return HttpResponseRedirect('/wikipedia/' + entrys)







def searchEntry(request):
    entries= util.list_entries()
    if request.method == "POST":

        results = []
        search = request.POST["search"]
        search = str(search)

        for entry in entries:

                if search == entry:
                    return HttpResponseRedirect('wikipedia/' + entry)

                if search.lower() in entry.lower():
                    results.append(entry)

        if results != []:
            return render(request, "encyclopedia/results.html", {
                'entries': results, 
                }) 
    return render(request, "encyclopedia/index.html", {
    "entries": util.list_entries(),
    })









def editEntry(request,entry):
    content = util.get_entry(entry)
    form = EditEntry(request.POST,initial={'body':content})
    print(request.POST)
    if request.method == "POST":
        print(request.POST)
        if form.is_valid():
            Title = request.POST['title']
            Body = request.POST['body']

            util.save_entry(Title, Body)

            return HttpResponseRedirect("/wikipedia/" + Title)
    
    return render(request, "encyclopedia/edit.html", { "title": entry, "body": content})

encyclopedia/templates/encyclopedia/create-entry.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ef.as_p}}
    <input type="submit" value="SaveEntry">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block content %}
{% block title %}
    {{ title }}
    
{% endblock %}

{% block body %}

<div class="container">
<table>
    <form method="POST">
        {% csrf_token %}
        <div>
            <input type="text" value="{{ title }}" name="title" class="form-control">
        </div>
        <div>
            <textarea name="body" class="form-control" rows="15">{{ body }}</textarea>
        </div>
        <button class="btn btn-success" type="submit">Edit</button>
    </form>
</table>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/entrys.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}
    {{ title }}
    
{% endblock %}

{% block body %}
        <p>{{entry | safe}}</p>
        
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    
        {% for entry in entries %}
            <a class="list-group-item" href="{% url 'wiki:entry-url' entry %}"> {{ entry }} </a>
        {% endfor %}
    
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="POST" action="{% url 'wiki:search-entry' %}">
                    {% csrf_token %}
                    <input class="search" type="text" name="search"  placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create-entry' %}">Create New Page</a> 
                </div>
                <div>
                    <a href="{% url 'wiki:random-entry' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    Search Results
{% endblock %}


{% block body %}
<h1>results:</h1>



<ul>
        {% for entry in entries %}
        <li class="list-group-item"><a href="{% url 'wiki:entry-url' entry %}"> {{ entry }} </a></li>
        {% endfor %}
    
</ul>
{% endblock %}

encyclopedia/templates/encyclopedia/saved.html
{% extends 'encyclopedia/layout.html' %}
{% block body %}
<h2 style="color:green;">{{entry}} Saved Succesfully</h2>
{% endblock body %}

encyclopedia/templates/encyclopedia/search-error.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
<h2 style="color:red;">No Page Found With The Name : {{entry}}</h2>
{% endblock body %}